---
title: "Proposal"
author: "Sakura Hu, Ruikang Wang, Peizeng Yuan"
date: "`r Sys.Date()`"
output: pdf_document
---

# Contributions
Sakura Hu:
Ruikang Wang:
Peizeng Yuan:

# Introduction

# Data Description

# Preliminary Results

# Bibliography

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
# Set CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org/"))
```

```{r}
#| echo: false
#| warning: false
#| message: false

# Install the NHANES package
install.packages("NHANES")

# Load the package
library(NHANES)
library(dplyr)
library(ggplot2)


# View available datasets
data(package = "NHANES")

# Load the main dataset
data(NHANES)

# Select only the columns you need and filter out rows with missing values
nhanes_data <- NHANES %>%
  select(BMI, Poverty, PhysActiveDays, Age, SleepHrsNight, Gender) %>%
  filter(!is.na(BMI), !is.na(Poverty), !is.na(PhysActiveDays), !is.na(Age), !is.na(SleepHrsNight), !is.na(Gender))


# Check the first few rows to make sure everything looks correct
head(nhanes_data)

```

```{r}
#| echo: false
#| warning: false
#| message: false

# Convert Gender to a factor (if not already)
nhanes_data$Gender <- as.factor(nhanes_data$Gender)
# Fit a linear model
lm_model <- lm(log(BMI) ~ Poverty + PhysActiveDays + Age + SleepHrsNight + Gender, data = nhanes_data)

# Summary of the model
summary(lm_model)

```


```{r}
#| echo: false
#| warning: false
#| message: false

fitted_values = fitted(lm_model)
residual_values = resid(lm_model)
     
plot(fitted_values, residual_values, 
     main = "Figure1: fitted versus residual values", 
     xlab = "Fitted", 
     ylab = "Residuals")
```


```{r}
fitted_values = fitted(lm_model)
sresidual_values = rstandard(lm_model)
     
plot(fitted_values, sresidual_values, 
     main = "Figure2: fitted versus Standardized Residuals values", 
     xlab = "Fitted", 
     ylab = "Standardized Residuals")
```


```{r}
hist(sresidual_values,
     main = "Figure3: Standardized residuals histogram",
     xlab = "Standardized residuals")
```

```{r}
# Set up the plotting area for a 2x3 grid (2 rows, 3 columns)
par(mfrow = c(2, 3))

# Plot residuals against Poverty
plot(nhanes_data$Poverty, residual_values, 
     main = "Figure4: Poverty vs. Residuals", 
     xlab = "Poverty", 
     ylab = "Residuals")

# Plot residuals against Age
plot(nhanes_data$Age, residual_values, 
     main = "Figure5: Age vs. Residuals", 
     xlab = "Age", 
     ylab = "Residuals")

# Plot residuals against Gender
plot(nhanes_data$Gender, residual_values, 
     main = "Figure6: Gender vs. Residuals", 
     xlab = "Gender", 
     ylab = "Residuals")

# Plot residuals against PhysActiveDays
plot(nhanes_data$PhysActiveDays, residual_values, 
     main = "NAHANES: Physical Active Days vs. Residuals", 
     xlab = "Physical Active Days", 
     ylab = "Residuals")

# Plot residuals against SleepHrsNight
plot(nhanes_data$SleepHrsNight, residual_values, 
     main = "NAHANES: Sleep Hours vs. Residuals", 
     xlab = "Sleep Hours", 
     ylab = "Residuals")

# Reset the plotting area to default
par(mfrow = c(1, 1))

```

```{r}
plot(nhanes_data[, c(1, 2, 3, 4, 5, 6)], col="cadetblue")
```
```{r}
BMI_values = log(nhanes_data$BMI)
fitted_values = fitted(lm_model)

plot(fitted_values, BMI_values,
     main = "Figure7: BMI versus regression fit",
     xlab = "Fitted values", ylab = "BMI")
abline(0, 1, 
       col=c("blue"), lty=1)
legend("bottomright", legend=c("y = x line"),
       col=c("blue"), lty=1)
```


```{r}
# Normal Q-Q plot
plot(lm_model, which = 2)


# Scatter plot for continuous variables
plot(nhanes_data$Age, log(nhanes_data$BMI), 
     main = "NAHANES: Physical Active Days vs. BMI", 
     xlab = "Age", 
     ylab = "BMI")


fit <- lm(log(nhanes_data$BMI) ~ nhanes_data$Age)

# Add the fitted regression line
abline(fit, col = "red", lwd = 2)


# Scatter plot for continuous variables
plot(nhanes_data$Gender, log(nhanes_data$BMI), 
     main = "NAHANES: Physical Active Days vs. Gender", 
     xlab = "Gender", 
     ylab = "BMI")

fit <- lm(log(nhanes_data$BMI) ~ nhanes_data$Gender)

# Add the fitted regression line
abline(fit, col = "red", lwd = 2)

plot(nhanes_data$Poverty, log(nhanes_data$BMI), 
     main = "NAHANES: Physical Active Days vs. Poverty", 
     xlab = "Poverty", 
     ylab = "BMI")

fit <- lm(log(nhanes_data$BMI) ~ nhanes_data$Poverty)

# Add the fitted regression line
abline(fit, col = "red", lwd = 2)

plot(nhanes_data$SleepHrsNight, log(nhanes_data$BMI), 
     main = "NAHANES: Physical Active Days vs. SleepHrsNight", 
     xlab = "SleepHrsNight", 
     ylab = "BMI")

fit <- lm(log(nhanes_data$BMI) ~ nhanes_data$SleepHrsNight)

# Add the fitted regression line
abline(fit, col = "red", lwd = 2)

plot(nhanes_data$PhysActiveDays, log(nhanes_data$BMI), 
     main = "NAHANES: Physical Active Days vs. PhysActiveDays", 
     xlab = "PhysActiveDays", 
     ylab = "BMI")
fit <- lm(log(nhanes_data$BMI) ~ nhanes_data$PhysActiveDays)

# Add the fitted regression line
abline(fit, col = "red", lwd = 2)

```

```{r}
# Plot histograms for each variable
par(mfrow = c(2, 3))  # Arrange plots in 2 rows and 3 columns
hist(nhanes_data$BMI, main="BMI Distribution", xlab="BMI", col="lightblue")
hist(nhanes_data$Poverty, main="Poverty Index Distribution", xlab="Poverty Index", col="lightgreen")
hist(nhanes_data$PhysActiveDays, main="Physical Activity Days Distribution", xlab="Phys Active Days", col="lightcoral")
hist(nhanes_data$Age, main="Age Distribution", xlab="Age", col="lightyellow")
hist(nhanes_data$SleepHrsNight, main="Sleep Hours Distribution", xlab="Sleep Hours", col="lightpink")
hist(as.numeric(nhanes_data$Gender), main="Gender Distribution", xlab="Gender (0=Female, 1=Male)", col="lightgray")
par(mfrow = c(1, 1))  # Reset plot layout
```




